CREATE SCHEMA IF NOT EXISTS nomen;

GRANT USAGE ON SCHEMA nomen TO "%[1]s";
GRANT ALL ON ALL TABLES IN SCHEMA nomen TO "%[1]s";
GRANT ALL ON ALL SEQUENCES IN SCHEMA nomen TO "%[1]s";
ALTER DEFAULT PRIVILEGES IN SCHEMA nomen GRANT ALL ON TABLES TO "%[1]s";
ALTER DEFAULT PRIVILEGES IN SCHEMA nomen GRANT ALL ON SEQUENCES TO "%[1]s";
