CREATE SCHEMA IF NOT EXISTS nomen_product;

GRANT USAGE ON SCHEMA nomen_product TO "%[1]s";
GRANT ALL ON ALL TABLES IN SCHEMA nomen_product TO "%[1]s";
GRANT ALL ON ALL SEQUENCES IN SCHEMA nomen_product TO "%[1]s";
ALTER DEFAULT PRIVILEGES IN SCHEMA nomen_product GRANT ALL ON TABLES TO "%[1]s";
ALTER DEFAULT PRIVILEGES IN SCHEMA nomen_product GRANT ALL ON SEQUENCES TO "%[1]s";
