syntax = "proto3";

package nomen.application.v2;

import "protoc-gen-openapiv2/options/annotations.proto";
import "nomen/application/v2/login.proto";

option go_package = "github.com/shippinAI/nomen/pkg/grpc/application/v2;application";

message SAMLConfiguration {
  // The Metadata XML is the provided or fetched metadata stored at Nomen.
  // If either the metadata was provided as XML or when Nomen fetched it at the provided URL,
  // it is stored here.
  bytes metadata_xml = 1;
  // The Metadata URL is the URL where the metadata was fetched from.
  // In case the metadata was provided as raw XML, this field is empty.
  string metadata_url = 2;

  // LoginVersion specifies the login UI, where the user is redirected to for authentication.
  // It can be used to select a specific login UI, e.g. for embedded UIs or for custom login pages
  // hosted on any other domain.
  // If unset, the login UI is chosen by the instance default.
  LoginVersion login_version = 3;
}
